[versions]
kotlin = "2.4.10"
jdk-version = "17"
ktfmt-gradle = "0.26.0"
jsoup = "1.22.2"
kotlinx-serialization = "1.11.0"
slf4j = "2.0.18"
kotest = "6.2.2"
mockk = "1.14.11"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-gradle" }
kotest = { id = "io.kotest", version.ref = "kotest" }

[libraries]
# Jsoup
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

# Kotlin libraries
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# SLF4J
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Kotest
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

# MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
